<SampleWidget>:
	orientation: 'vertical'
	Scatter:
		canvas.before:
			Color:
				rgba: root.colour
	
			Rectangle:
				size: 100,100
				pos: 200,200
		
			Ellipse:
				size: 200, 200
				pos: 150,300

	TextInput:
		id:id1
		size_hint_y: None
		font_size:100
		height: 100
		text: 'OM'
		on_text: root.sample()
	
	FloatLayout:
		orientation: 'horizontal'
		Scatter:
			Label:
				id:id2
				text: id1.text
				height:100
				font_size: 100								
				color: root.colour
						
	
			
